spring:
  application:
    name: hrms-leave
  datasource:
    url: ${LEAVE_DB_URL:jdbc:postgresql://localhost:5432/hrms_leave}
    username: ${LEAVE_DB_USER:postgres}
    password: ${LEAVE_DB_PASSWORD:root@2025}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 24 hours
  refresh-token:
    expiration: 604800000 # 7 days

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.cre.hrms: DEBUG
    org.springframework: INFO
